version: '3.4'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: aspnetcore.development.dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "4200:4200"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge


